### PR TITLE
Feature: Added `onTriggerClick` prop callback

### PR DESCRIPTION
**Pull request by armand1m**
Now the developer can hook callbacks into the TriggerClick handler from `react-collapsible` using a `onTriggerClick` prop.

### CODE REVIEW

**Comment by armand1m** [comment]
The documentation has been modified in the PR #11

**Comment by armand1m** [comment]
Thanks for merging it back =) it is already released in the npm registry?

**Comment by glennflanagan** [comment]
Not yet. I need to cut a new release. I can't do it today but I'll try and get it done over the weekend some time.

**Comment by armand1m** [comment]
May I configure `semantic-release` on this project for this project and you just configure the right keys on travis?

**Comment by armand1m** [comment]
Hey @glennflanagan, it has been a while since then. Did you already got time to run `npm publish` with a new version of this?

**Pull request merged**
