### PR TITLE
Allow open Collapsible element to be closed without opening another element.

### PR DESCRIPTION
**Pull request by starsinmypockets**
Add 'closeable' prop which allows second click on accordion data-trigger to close the collapsible element.

### CODE REVIEW

**Comment by heavybeard** [comment]
@glennflanagan you think you can merge this PR?

**Review by glennflanagan — CHANGES_REQUESTED** [review]
This looks good to me, however a change to move over to the PropTypes library means you have merge conflicts. Could you resolve the conflicts and I can merge. Cheers.

**Comment by glennflanagan** [comment]
Could you add some notes to the README.md for the new feature too please?

**Comment by starsinmypockets** [comment]
Will do :)

**Comment by starsinmypockets** [comment]
I no longer have write privileges to my old fork so I created a new PR here:
https://github.com/glennflanagan/react-responsive-accordion/pull/9

**Pull request closed without merging**
